# Generated by Django 5.2.8 on 2026-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirecord',
            name='age',
            field=models.IntegerField(blank=True, help_text='年齡', null=True),
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='bmr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bmirecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
