# Generated by Django 5.2.8 on 2026-02-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0002_bmirecord_age_bmirecord_bmr_bmirecord_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmirecord',
            name='user',
        ),
    ]
